apiVersion: v1
kind: Service
metadata:
  labels:
    app: volume-exporter
    release: volume-exporter
  name: volume-exporter
  namespace: kube-system
spec:
  ports:
  - name: http
    port: 9876
    protocol: TCP
    targetPort: 9876
  selector:
    app: volume-exporter
    release: volume-exporter
  sessionAffinity: None
  type: ClusterIP