apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: volume-exporter
    release: volume-exporter
  name: volume-exporter
  namespace: kube-system
spec:
  endpoints:
  - honorLabels: true
    port: http
  jobLabel: app
  selector:
    matchLabels:
      app: volume-exporter
      release: volume-exporter