apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: volume-exporter
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: volume-exporter
      release: volume-exporter
  template:
    metadata:
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ""
      creationTimestamp: null
      labels:
        app: volume-exporter
        release: volume-exporter
    spec:
      containers:
      - name: volume-exporter
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        image: reg.kpaas.io/kpaas/volume-exporter:v0.0.1
        imagePullPolicy: IfNotPresent
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/kubelet
          name: kubelet
          readOnly: true
          mountPropagation: HostToContainer
      dnsPolicy: ClusterFirst
      hostNetwork: true
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      - operator: Exists
      volumes:
      - hostPath:
          path: /var/lib/kubelet
          type: ""
        name: kubelet
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
